/**
 * A defensive barrier boss attack that blocks player-fired projectiles for 2 seconds.
 * The shield is positioned at world coordinates (717, 364) directly in front of the
 * boss panel, covering a 120×40 pixel rectangle. Any {@link Projectile} fired by the
 * player that intersects the shield rectangle is immediately deactivated.
 *
 * <p>Architecture role: {@code Shield} is one of the five {@link BossAttack} subtypes
 * that the Apprentice can trigger via the boss control panel (the others are
 * {@link SearingBeam}, {@link BlockRain}, {@link SpikeArray}, and {@link CrusherBlock}).
 * It is instantiated by the boss-attack factory in {@link GameStarter} or
 * {@link GameServer} and added to the active-element list for the duration of its
 * 2-second lifetime. The attack has a purely defensive role: it intercepts the
 * Wanderer's ranged attacks while the boss prepares a follow-up offensive attack.</p>
 *
 * <p>Rendering: The shield is drawn as a semi-transparent gold rectangle (alpha 0.25)
 * with a brighter gold 1.5 px border, matching the game's gold-and-dark colour palette.
 * The fill's low alpha is intentional: the player can see the shield but cannot shoot
 * through it, creating a visual cue that discourages wasting projectiles.</p>
 *
 * @author [YOUR NAME]
 * @id [YOUR ID]
 * @date 2026-03-21
 * @certification I certify that this code is my own work and has not been copied from
 *                any other source, in whole or in part.
 */

import java.awt.AlphaComposite;  // Provides SRC_OVER compositing mode for drawing the semi-transparent fill and fully-opaque border
import java.awt.BasicStroke;      // Configures the stroke width (1.5 px) for the gold border outline
import java.awt.Color;            // AWT colour for the semi-transparent gold fill (#c9a84c) and bright gold border (#f0cc7a)
import java.awt.Composite;        // Interface type saved before and restored after alpha compositing, preserving caller's composite state
import java.awt.Graphics2D;       // 2D rendering context passed to render(); used for fillRect and drawRect with composite/stroke settings
import java.awt.Rectangle;        // AWT rectangle for the shield hitbox (shieldRect) used in intersection tests with projectile bounds
import java.awt.Stroke;           // Interface type saved before and restored after setting the 1.5 px BasicStroke
import java.util.List;            // List interface for the projectiles reference; checked each tick for player-fired projectiles to intercept

public class Shield extends BossAttack { // Extends BossAttack for the shared active-flag, lifetime timer, and super.update() duration management

    /**
     * The world-space bounding rectangle of the shield barrier used for projectile
     * interception. Positioned at (717, 364) and sized 120×40 to cover the approach
     * lane in front of the boss panel.
     *
     * <p>Interaction: Compared against each active {@link Projectile#getBounds()} in
     * {@link #update(long)} via {@link Rectangle#intersects(Rectangle)} to detect hits.
     * Mirrors the AABB passed to {@code super()} so the {@link BossAttack}'s inherited
     * bounds are consistent with the explicit interception rectangle.</p>
     */
    private Rectangle shieldRect; // Explicit Rectangle for intersection tests; set to the same (717,364,120,40) as the super() AABB

    /**
     * Reference to the game's live projectile list. Iterated every tick while the
     * shield is active to deactivate any player-fired projectile that enters the zone.
     *
     * <p>Interaction: Provided at construction time by the boss-attack factory in
     * {@link GameStarter}. The list is the same {@code List<Projectile>} that
     * {@link GameStarter} manages; modifying projectile active-states here has
     * immediate effect on the game loop's update/render passes.</p>
     */
    private List<Projectile> projectiles; // Live reference to GameStarter's projectile list; iterated in update() to intercept player shots

    /**
     * Constructs a new {@code Shield} at the fixed boss-panel position (717, 364)
     * with a 120×40 pixel hitbox and a 2-second lifetime.
     *
     * <p>Architecture role: The position and lifetime are hard-coded to match the
     * boss arena layout generated by {@link BossArenaGenerator}. The 2-second
     * duration (2000 ms) matches the standard boss-attack window, after which
     * {@link BossAttack#update(long)} sets {@link GameElement#active} to {@code false}
     * and the shield disappears without further intervention.</p>
     *
     * <p>Interaction: Called by the boss-attack factory when the Apprentice selects
     * the Shield action on the boss control panel. The {@code projectiles} list is
     * passed in so {@link #update(long)} can access the live projectile roster without
     * holding a reference to {@link GameStarter}.</p>
     *
     * @param projectiles the list of active projectiles to check for interception;
     *                    may be {@code null} (the update loop guards against this)
     */
    public Shield(List<Projectile> projectiles) {                  // Single-argument constructor: receives the live projectile list; position/size/lifetime are fixed
        super(717, 364, 120, 40, 2000L);                           // Delegate to BossAttack: place at (717,364), set 120×40 AABB, start 2000 ms countdown
        this.shieldRect = new Rectangle(717, 364, 120, 40);        // Construct an explicit Rectangle matching the super AABB for use in projectile intersection tests
        this.projectiles = projectiles;                             // Store live projectile list reference; iterated in update() to detect player-shot interceptions
    }

    /**
     * Advances the shield's lifetime timer and intercepts any player-fired projectiles
     * that overlap the shield rectangle. When the lifetime expires (after 2000 ms),
     * the inherited {@link BossAttack#update(long)} sets {@code active} to {@code false}
     * and this method returns immediately on the next tick.
     *
     * <p>Architecture role: Called every 16 ms by the game loop in {@link GameStarter}
     * for every active element. The interception loop runs in O(n) over the projectile
     * list each tick, which is acceptable because the maximum number of in-flight
     * projectiles is small (bounded by fire rate and level size).</p>
     *
     * <p>Interaction: Calls {@link BossAttack#update(long)} first to manage the lifetime
     * counter; then checks {@code active} to bail early if the shield just expired.
     * For each intercepted projectile, {@link Projectile#setActive(boolean)} is called
     * with {@code false} so the game loop will skip it in subsequent ticks, effectively
     * removing it from play without mutating the list during iteration.</p>
     *
     * @param deltaMs the time elapsed since the last tick, in milliseconds; forwarded
     *                to {@code super.update()} for lifetime countdown management
     */
    @Override
    public void update(long deltaMs) {            // Override to add projectile-interception logic on top of the inherited lifetime management
        super.update(deltaMs);                    // Let BossAttack.update() decrement the lifetime timer and set active=false when expired
        if (!active) {                            // Early-exit guard: if super.update() just expired the shield, skip the projectile scan
            return;                               // Return immediately; shield is no longer blocking anything
        }

        if (projectiles != null) {                // Null guard: projectiles list may be null if the factory was called without a live roster
            for (Projectile proj : projectiles) { // Iterate every projectile in the game's live list each tick while the shield is active
                if (proj.isActive() && proj.isFromPlayer()              // Only intercept active projectiles that were fired by the player (not boss-spawned)
                        && proj.getBounds().intersects(shieldRect)) {   // Check AABB intersection: projectile's bounds overlap the 120×40 shield rectangle
                    proj.setActive(false);                              // Deactivate the projectile: it is absorbed by the shield and will not reach the boss
                }
            }
        }
    }

    /**
     * Renders the shield as a semi-transparent gold rectangle with a fully opaque
     * gold border. The composite and stroke state of the provided {@link Graphics2D}
     * context are saved and fully restored after drawing so subsequent render calls
     * are not affected.
     *
     * <p>Architecture role: Called every frame by {@link GameCanvas#renderElements}
     * for every active element. The two-pass draw (fill then stroke) matches the
     * visual language used by other boss-arena UI elements: a translucent interior
     * to indicate area effect with a solid edge to define the boundary precisely.</p>
     *
     * <p>Interaction: Uses {@link AlphaComposite#SRC_OVER} for both passes: the fill
     * pass uses alpha 0.25 (25% opaque warm gold) for a ghostly shimmer; the stroke
     * pass uses alpha 1.0 (fully opaque bright gold) for a crisp visible border.
     * The saved/restored composite and stroke ensure no leakage into adjacent render
     * calls (e.g. player sprite, HUD, platform tiles).</p>
     *
     * @param g the {@link Graphics2D} context to draw on; must not be {@code null};
     *          its transform is already in world space via the Camera offset applied
     *          by {@link GameCanvas#renderBoss}
     */
    @Override
    public void render(Graphics2D g) {                                                         // Override BossAttack.render() to draw the shield's visual representation
        if (!active) {                                                                         // Do not render if the shield has expired (active set false by super.update())
            return;                                                                            // Early exit: expired shields are invisible
        }

        Composite originalComposite = g.getComposite();                                       // Save the caller's composite so we can restore it after alpha-composited draws
        Stroke originalStroke = g.getStroke();                                                 // Save the caller's stroke so our 1.5 px setting does not leak into later renders

        // Fill — semi-transparent gold
        g.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.25f));           // Apply 25% opacity: warm gold fill appears ghostly, hinting the barrier without fully blocking the view
        g.setColor(new Color(0xc9, 0xa8, 0x4c));                                              // Warm gold fill colour #c9a84c — matches the Portal frame and HUD accent colour
        g.fillRect(shieldRect.x, shieldRect.y, shieldRect.width, shieldRect.height);          // Fill the shield rectangle at (717,364) with size 120×40 at 25% opacity

        // Stroke — gold border
        g.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 1.0f));           // Restore full opacity for the border so it appears as a crisp solid line
        g.setColor(new Color(0xf0, 0xcc, 0x7a));                                              // Bright gold border colour #f0cc7a — lighter than the fill to create a glowing-edge effect
        g.setStroke(new BasicStroke(1.5f));                                                    // 1.5 px stroke for a fine but visible outline that complements the translucent fill
        g.drawRect(shieldRect.x, shieldRect.y, shieldRect.width, shieldRect.height);          // Outline the shield rectangle with the bright gold 1.5 px stroke

        g.setComposite(originalComposite);                                                     // Restore caller's composite mode to prevent alpha leakage into subsequent render calls
        g.setStroke(originalStroke);                                                           // Restore caller's stroke width so adjacent draw calls use their own intended stroke
    }
}
